{
  /* tableData.jsx */
}

export const columns = [
  { Header: '削除/修正', accessor: 'chkbox' },
  { Header: '装置識別ID', accessor: 'IdentificationNumber' },
  { Header: '機種', accessor: 'DeviceType' },
  { Header: '装置識別名', accessor: 'IdentificationName' },
  { Header: '設置場所(県)', accessor: 'prefecture' },
  { Header: '設置場所(市)', accessor: 'city' },
  { Header: '設置場所（表示名', accessor: 'InstallationLocation' },
  { Header: '製品カテゴリ', accessor: 'ProductCategory' },
  { Header: '製品名', accessor: 'ProductRevision' },
  { Header: '装置グループ名', accessor: 'DeviceGroupName' },
  { Header: 'スタックメンバ－番号', accessor: 'StackMemberNumber' },
  { Header: '出荷情報の存在有無チェック', accessor: 'SerialNumberCheckTarget' },
  { Header: '登録結果', accessor: 'result' },
];

export const data = [
  {
    chkbox: false,
    IdentificationNumber: 1,
    DeviceType: 'CISCO',
    IdentificationName: 'abk-sdwan01',
    prefecture: '東京',
    city: '府中市',
    InstallationLocation: 'NEC東京都府中ビル',
    ProductCategory: 'ネットワーク機器',
    ProductRevision: 'asr-1001x',
    DeviceGroupName: '関東地方',
    StackMemberNumber: null,
    SerialNumberCheckTarget: true,
    result: null,
  },
  {
    chkbox: false,
    IdentificationNumber: 2,
    DeviceType: 'CISCO',
    IdentificationName: 'WS-C2960X-48FPS-L',
    prefecture: '大阪',
    city: '大阪市',
    InstallationLocation: '関西OBP事業所',
    ProductCategory: 'ネットワーク機器',
    ProductRevision: 'cat2960x',
    DeviceGroupName: '関西地方',
    StackMemberNumber: 1,
    SerialNumberCheckTarget: true,
    result: null,
  },
  {
    chkbox: false,
    IdentificationNumber: 3,
    DeviceType: 'CISCO',
    IdentificationName: 'WS-C2960X-48TS-L',
    prefecture: '大阪',
    city: '大阪市',
    InstallationLocation: '関西OBP事業所',
    ProductCategory: 'ネットワーク機器',
    ProductRevision: 'cat2960x',
    DeviceGroupName: '関西地方',
    StackMemberNumber: 2,
    SerialNumberCheckTarget: true,
    result: null,
  },
  {
    chkbox: false,
    IdentificationNumber: 4,
    DeviceType: 'CISCO',
    IdentificationName: 'C9120AXI-EWC-Q',
    prefecture: '神奈川県',
    city: '川崎市',
    InstallationLocation: '多摩川事業所',
    ProductCategory: 'ネットワーク機器',
    ProductRevision: 'C9120AXI',
    DeviceGroupName: '関東地方',
    StackMemberNumber: null,
    SerialNumberCheckTarget: true,
    result: null,
  },
];
